### ISSUE TITLE
xrange called, which errors in Python 3

### ISSUE THREAD

**Issue by stin7** [jsilter/parametric_tsne#1]
Thanks for publishing this code, excited to try it out. Running into an error with xrange:

Toy code:

    import numpy as np
    from parametric_tSNE import Parametric_tSNE

    X = np.array([[1,0,1],
              [0,1,0]
             ])

    ptsne = Parametric_tSNE(3, 2, 5)
    ptsne.fit(X)

Results in error:

    parametric_tSNE/utils.py in calc_betas_loop(indata, perplexity, tol, max_tries)
    132     in_sq_diffs = get_squared_cross_diff_np(indata)
    133  
    --> 134     loop_samps = xrange(num_samps)
    135     for ss in loop_samps:
    136         betamin = -np.inf

    NameError: name 'xrange' is not defined

IIUC, `xrange` in Py2 became `range` in Py3. Is your code intended for Py2 or 3?

Thanks

**Comment by jsilter** [comment]
I developed it on Python 2.7. I just changed 'xrange' to 'range' in the code though (the performance hit in python 2.7 should be small/negligible it's just that xrange is a force of habit for me) and did some test runs on Python 3, it worked on my machine :-). Try that out and let me know if it works.

**Comment by stin7** [comment]
Thanks for the quick look! Works for me now, will let you know if I run into anything else

Thanks again.
